Algoritmo "semnome"

Var
franquia: caracter
heroimarvel: caracter
heroidc: caracter



Inicio

escrevaL(" Qual você mais curte, Marvel ou DC?")
leia (franquia)

se franquia = "marvel" entao
   escreval(" Cap America ou Homem de Ferro")
   leia(heroimarvel)
   escreval(" o Super Heroi escolhido foi o = ", heroimarvel)

senao
     escreval(" Batman ou Superman?")
     leia(heroidc)
     escreval(" o Super Heroi escolhido foi o = ", heroidc)
fimse

Fimalgoritmo