Algoritmo "39"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/10/2020
Var

// Série de Fibonacci
a: inteiro
b: inteiro
c: inteiro
i: inteiro

Inicio

a <- 1
b <- 0
c <- 0
para i de 0 ate 19 faca
escreval(c)
c <- a + b
a <- b
b <- c



fimpara


Fimalgoritmo