Algoritmo "58"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/11/2020
Var
numeros: vetor [1..100] de inteiro
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para i  de 1 ate 100 faca
numeros[i] <- i + 99
fimpara

para i  de 1 ate 100 faca
escreval(numeros[i] )
fimpara

Fimalgoritmo