Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/02/2021
Var
x, idade: inteiro

inicio

para x de 1 ate 15 faca
   escreval("Digite a idade: ")
   leia(idade)
   se idade >= 18 entao
      escreval("Fulano é maior de idade")
   fimse
fimpara
Fimalgoritmo